version: '3'

services:
  server:
    image: spotify-radio
    build: .
    container_name: jsexpert-docker
    restart: always
    stdin_open: true
    tty: true
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      CHOKIDAR_INTERVAL: 300
    ports:
      - 3000:3000
    volumes:
      - ./:/data/app
      - /data/app/node_modules
